export const LOADING_FOLDER_STRUCTURE = 'LOADING_FOLDER_STRUCTURE';
export const DONE_LOADING_FOLDER_STRUCTURE = 'DONE_LOADING_FOLDER_STRUCTURE';
export const FOLDER_STRUCTURE = 'FOLDER_STRUCTURE';
export const ERROR_FETCHING_FILES = 'ERROR_FETCHING_FILES';
